name: panda_test
channels:
- conda-forge
dependencies:
- numpy
- opencv
- pyrealsense2
- python=3.9
- scipy
- threadpoolctl
- pip:
  - atomics==1.0.3
  - certifi==2025.8.3
  - cffi==1.17.1
  - charset-normalizer==3.4.3
  - docstring_parser==0.17.0
  - dynamixel-sdk==3.7.31
  - eval_type_backport==0.2.2
  - idna==3.10
  - importlib_metadata==8.7.0
  - markdown-it-py==3.0.0
  - mdurl==0.1.2
  - opencv-python==4.12.0
  - opencv-python-headless==4.12.0
  - panda-python==0.8.1
  - pycparser==2.22
  - Pygments==2.19.2
  - pyserial==3.5
  - reactivex==4.0.4
  - requests==2.32.4
  - rich==14.1.0
  - shtab==1.7.2
  - typeguard==4.4.4
  - typing_extensions==4.14.1
  - tyro==0.9.28
  - urllib3==2.5.0
  - websockets==15.0.1
  - zipp==3.23.0

